name: Build and Deploy Docker

on:
  push:
    branches:
      - main

  schedule:
    - cron: "0 0 * * 1"   # Weekly rebuild
    
jobs:
  jammy:
    runs-on: ubuntu-latest
    steps:
      - name: Step One - Checkout Repository
        uses: actions/checkout@v3

      - name: Step Two - Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'arm64'

      - name: Step Three - Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Step Four - Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Step Five - Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: jammy/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/ubuntu:22.04

  noble:
    runs-on: ubuntu-latest
    steps:
      - name: Step One - Checkout Repository
        uses: actions/checkout@v3

      - name: Step Two - Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'arm64'

      - name: Step Three - Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Step Four - Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Step Five - Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: noble/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/ubuntu:24.04